# Generated by Django 3.2.4 on 2021-06-25 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ResultApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentclass',
            old_name='students',
            new_name='student',
        ),
        migrations.RenameField(
            model_name='studentsubject',
            old_name='student',
            new_name='students',
        ),
    ]
