# Generated by Django 3.2.4 on 2021-07-01 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ResultApp', '0003_auto_20210626_0051'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subjects',
            old_name='descripton',
            new_name='description',
        ),
    ]
